I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 16, in script call
    call prologue
  File "game/script.rpy", line 258, in script call
    pause
  File "game/script.rpy", line 302, in script
    label sub_money(x):
TypeError: Missing required positional arguments: 'x'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 16, in script call
    call prologue
  File "game/script.rpy", line 258, in script call
    pause
  File "game/script.rpy", line 302, in script
    label sub_money(x):
  File "/Users/ruthwu/Desktop/renpy-8.0.3-sdk/renpy/ast.py", line 1072, in execute
    values = apply_arguments(self.parameters, renpy.store._args, renpy.store._kwargs)
  File "/Users/ruthwu/Desktop/renpy-8.0.3-sdk/renpy/ast.py", line 294, in apply_arguments
    return parameters.apply(args, kwargs, ignore_errors)
  File "/Users/ruthwu/Desktop/renpy-8.0.3-sdk/renpy/ast.py", line 230, in apply
    raise TypeError(
TypeError: Missing required positional arguments: 'x'

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
Begonia Grove 1.0
Sat Nov  5 20:23:24 2022
